swagger: "2.0"
info:
  version: 1.0.0
  title: Hello World
  description: Hello World

consumes:
  - application/json
produces:
  - application/json

definitions:
  person:
    type: object
    required:
      - name
      - message
    properties:
      name:
        type: string
        minLength: 4
        pattern: "^[a-zA-Z0-9- ]+$"
      message:
        type: array
        uniqueItems: true
        items:
            type: string
            minLength: 1
            pattern: "^[a-zA-Z0-9- ]+$"

parameters:
  personName:
    name: personName
    in: path
    description: Name of the person
    required: true
    type: string

paths:
  /people:
    get:
      description: Returns all people, optionally filtered by one or more criteria
      operationId: findPeople
      parameters: &peopleFilters
        - name: name
          in: query
          description: Filters people by name
          required: false
          type: string
        - name: message
          in: query
          description: Filters people by message
          required: false
          type: array
          items:
            type: string
          uniqueItems: true
          collectionFormat: csv
      responses:
        default:
          description: Returns the matching people
          schema:
            type: array
            items:
              $ref: "#/definitions/person"
          headers:
            last-modified:
              type: string
              description: The date/time that a person was last modified

    delete:
      description: Deletes all people, optionally filtered by one or more criteria
      operationId: deletePeople
      parameters: *peopleFilters
      responses:
        default:
          description: Returns the people that were deleted
          schema:
            type: array
            items:
              $ref: "#/definitions/person"

    post:
      description: Creates a new person
      operationId: addPerson
      parameters:
        - name: person
          in: body
          description: The person to add
          required: true
          schema:
            $ref: "#/definitions/person"
      responses:
        201:
          description: Returns the newly-added person
          schema:
            $ref: "#/definitions/person"
          headers:
            Location:
              type: string
              description: The URL of the newly-added person

  /people/{personName}:
    parameters:
      - $ref: "#/parameters/personName"

    get:
      description: Returns a person by name
      operationId: findPersonByName
      responses:
        default:
          description: Returns the person data
          schema:
            $ref: "#/definitions/person"
          headers:
            last-modified:
              type: string
              description: The date/time that the person was last modified

    delete:
      description: Deletes a single person based on the name supplied
      operationId: deletePerson
      responses:
        default:
          description: Returns the person that was deleted
          schema:
            $ref: "#/definitions/person"

    patch:
      description: Updates a person by name
      parameters:
        - name: person
          in: body
          description: The updated person info
          required: true
          schema:
            $ref: "#/definitions/person"
      responses:
        default:
          description: Returns the updated person data
          schema:
            $ref: "#/definitions/person"

  /people/{personName}/photos:
    parameters:
      - $ref: "#/parameters/personName"

    post:
      description: Upload a new person photo
      operationId: addPersonPhoto
      consumes:
        - multipart/form-data
      parameters:
        - name: id
          in: formData
          description: The photo ID (generated automatically)
          type: integer
          format: int32
          minimum: 1
        - name: label
          in: formData
          description: A label for the photo
          required: true
          type: string
          minLength: 1
        - name: description
          in: formData
          description: An optional description of the photo
          type: string
        - name: photo
          in: formData
          description: The person photo
          required: true
          type: file
          minLength: 1
          maxLength: 5000000  # ~5MB
      responses:
        default:
          description: Returns the photo information
          schema:
            type: object
            properties:
              id:
                type: integer
                format: int32
                description: The auto-generated photo ID
              label:
                type: string
              description:
                type: string
              photo:
                type: object
                description: Information about the photo (size, file name, etc.)
          headers:
            Location:
              type: string
              description: The URL of the newly-added photo

    get:
      description: Get a list of the photos for a person
      responses:
        200:
          description: Returns the list of photos
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                  description: The auto-generated photo ID
                label:
                  type: string
                description:
                  type: string
                photo:
                  type: object
                  description: Information about the photo (size, file name, etc.)

  /people/{personName}/photos/{id}:
    parameters:
      - $ref: "#/parameters/personName"
      - name: id
        in: path
        description: The ID of the photo
        required: true
        type: integer
        format: int32

    get:
      description: Gets a person photo
      operationId: getPersonPhoto
      produces:
        - image/jpeg
        - image/gif
        - image/png
        - image/bmp
      responses:
        default:
          description: Returns the person photo
          schema:
            type: file

    delete:
      description: Deletes a person photo
      operationId: deletePersonPhoto
      responses:
        default:
          description: The photo was deleted successfully

  /:
    get:
      produces:
        - text/html
      responses:
        default:
          description: Hello World homepage
          schema:
            type: file
            default:
              $ref: index.html
